<a href="https://colab.research.google.com/github/Qbaxxx/Metody_analizy_danych_LAB_JBabinski/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
# Zadanie 1
tablica = np.arange(2, 34, 2).reshape(4, 4)

typ_danych = tablica.dtype
liczba_elementow = tablica.size
rozmiar_elementu = tablica.itemsize
zaalokowana_pamiec = tablica.nbytes

print("Tablica: ")
print(tablica)
print("\nTyp danych: ", typ_danych)
print("Liczba elementów: ", liczba_elementow)
print("Rozmiar elementu (w bajtach): ", rozmiar_elementu)
print("Łączna ilość zaalokowanej pamięci (w bajtach): ", zaalokowana_pamiec)

Tablica: 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Typ danych:  int64
Liczba elementów:  16
Rozmiar elementu (w bajtach):  8
Łączna ilość zaalokowanej pamięci (w bajtach):  128


In [13]:
# Zadanie 2
widok_tablicy = tablica.view().astype(np.uint8)

czy_widok = widok_tablicy.base is not None

typ_danych = tablica.dtype
liczba_elementow = tablica.size
rozmiar_elementu = tablica.itemsize
zaalokowana_pamiec = tablica.nbytes

print("Tablica:")
print(widok_tablicy)
print("\nCzy tablica jest widokiem:", czy_widok)
print("Typ danych:", typ_danych)
print("Liczba elementów:", liczba_elementow)
print("Rozmiar pojedynczego elementu (w bajtach):", rozmiar_elementu)
print("Łączna ilość zaalokowanej pamięci (w bajtach):", zaalokowana_pamiec)

Tablica:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Czy tablica jest widokiem: False
Typ danych: int64
Liczba elementów: 16
Rozmiar pojedynczego elementu (w bajtach): 8
Łączna ilość zaalokowanej pamięci (w bajtach): 128


In [14]:
# Zadanie 3
tablica_widok = tablica[1:3, 1:3]

tablica_kopia = tablica[1:3, 1:3].copy()

typ_danych = widok_tablicy.dtype
liczba_elementow = widok_tablicy.size
rozmiar_elementu = widok_tablicy.itemsize
zaalokowana_pamiec = widok_tablicy.nbytes


print("Tablica:")
print(widok_tablicy)
print("\nCzy tablica jest widokiem:", czy_widok)
print("Typ danych:", typ_danych)
print("Liczba elementów:", liczba_elementow)
print("Rozmiar pojedynczego elementu (w bajtach):", rozmiar_elementu)
print("Łączna ilość zaalokowanej pamięci (w bajtach):", zaalokowana_pamiec)

print("\nObszar 2x2 jako widok:")
print(tablica_widok)

print("\nObszar 2x2 jako kopia:")
print(tablica_kopia)

Tablica:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

Czy tablica jest widokiem: False
Typ danych: uint8
Liczba elementów: 16
Rozmiar pojedynczego elementu (w bajtach): 1
Łączna ilość zaalokowanej pamięci (w bajtach): 16

Obszar 2x2 jako widok:
[[12 14]
 [20 22]]

Obszar 2x2 jako kopia:
[[12 14]
 [20 22]]


In [15]:
# Zadanie 4
tablica = np.tile(np.array([1, 2, 3, 4]), (4, 1))

tablica_lustrzana = tablica[:, ::-1]

tablica_polaczona = np.hstack((tablica, tablica_lustrzana))

widok_tablicy = tablica.view().astype(np.uint8)

czy_widok = widok_tablicy.base is not None

tablica_widok = tablica[1:3, 1:3]

tablica_kopia = tablica[1:3, 1:3].copy()

typ_danych = widok_tablicy.dtype
liczba_elementow = widok_tablicy.size
rozmiar_elementu = widok_tablicy.itemsize
zaalokowana_pamiec = widok_tablicy.nbytes

print("Tablica:")
print(widok_tablicy)
print("\nCzy tablica jest widokiem:", czy_widok)
print("Typ danych:", typ_danych)
print("Liczba elementów:", liczba_elementow)
print("Rozmiar pojedynczego elementu (w bajtach):", rozmiar_elementu)
print("Łączna ilość zaalokowanej pamięci (w bajtach):", zaalokowana_pamiec)

print("\nObszar 2x2 jako widok:")
print(tablica_widok)

print("\nObszar 2x2 jako kopia:")
print(tablica_kopia)

print("\nTablica 4x4 z wartościami 1,2,3,4 w każdym wierszu:")
print(tablica)

print("\nWersja lustrzana tablicy w poziomie:")
print(tablica_lustrzana)

print("\nPołączona tablica:")
print(tablica_polaczona)

Tablica:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Czy tablica jest widokiem: False
Typ danych: uint8
Liczba elementów: 16
Rozmiar pojedynczego elementu (w bajtach): 1
Łączna ilość zaalokowanej pamięci (w bajtach): 16

Obszar 2x2 jako widok:
[[2 3]
 [2 3]]

Obszar 2x2 jako kopia:
[[2 3]
 [2 3]]

Tablica 4x4 z wartościami 1,2,3,4 w każdym wierszu:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Wersja lustrzana tablicy w poziomie:
[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]

Połączona tablica:
[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


In [16]:
# Zadanie 5
Z_5 = np.ones((2, 2), dtype=int)

Z_5_2 = Z_5 * 2
Z_5_3 = Z_5 * 3
Z_5_4 = Z_5 * 4

tablica_finalna = np.vstack((np.hstack((Z_5, Z_5_2)), np.hstack((Z_5_3, Z_5_4))))

print("Finalna tablica 4x4:")
print(tablica_finalna)

Finalna tablica 4x4:
[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
