<a href="https://colab.research.google.com/github/Qbaxxx/Metody_analizy_danych_LAB_JBabinski/blob/main/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pickle
import timeit

In [3]:
# Zad 1
"""Stwórz tablicę o nazwie
 a_small_one o wymiarach 8x8 z
 wartościami od 1 do 64."""

'Stwórz tablicę o nazwie\n a_small_one o wymiarach 8x8 z\n wartościami od 1 do 64.'

In [4]:
a_small_one = np.arange(1, 65).reshape(8, 8)
print(a_small_one)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [5]:
# Zad 2
"""Dla tablicy a_small_one policz:

sumę dla każdej kolumny,
sumę skumulowaną dla każdego wiersza,
wartość średnią dla każdego wiersza,"""

'Dla tablicy a_small_one policz:\n\nsumę dla każdej kolumny,\nsumę skumulowaną dla każdego wiersza,\nwartość średnią dla każdego wiersza,'

In [6]:
print(a_small_one.sum(axis=0))
print(a_small_one.cumsum(axis=1))
print(a_small_one.mean(axis=1))

[232 240 248 256 264 272 280 288]
[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]
[ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


In [7]:
# Zad 3
"""Zwróć podtablicę z tablicy
 a_small_one z elementami
  parzystymi (nie nadpisuj tej zmiennej)."""

'Zwróć podtablicę z tablicy\n a_small_one z elementami\n  parzystymi (nie nadpisuj tej zmiennej).'

In [8]:
print(a_small_one[a_small_one % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


In [9]:
# Zad 4
"""Zapisz do zmiennej o nazwie
 no_even_small_one
 tablicę a_small_one
  zamieniając wartości
  parzyste na wartość np.nan.
"""

'Zapisz do zmiennej o nazwie\n no_even_small_one\n tablicę a_small_one\n  zamieniając wartości\n  parzyste na wartość np.nan.\n'

In [10]:
no_even_small_one = np.where(a_small_one % 2 == 0, np.nan, a_small_one)
print(no_even_small_one)

[[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. nan]
 [49. nan 51. nan 53. nan 55. nan]
 [57. nan 59. nan 61. nan 63. nan]]


In [11]:
# Zad 5
"""Dla tablicy no_even_small_one policz
funkcjami uwzględniającymi wartości
nan (zazwyczaj posiadają przedrostek nan):

sumę dla każdego wiersza,
średnią dla każdej kolumny,
wartość najmniejszą i w całej tablicy,"""

'Dla tablicy no_even_small_one policz\nfunkcjami uwzględniającymi wartości\nnan (zazwyczaj posiadają przedrostek nan):\n\nsumę dla każdego wiersza,\nśrednią dla każdej kolumny,\nwartość najmniejszą i w całej tablicy,'

In [12]:
row_sums = np.nansum(no_even_small_one, axis=1)

col_means = np.nanmean(no_even_small_one, axis=0)

min_value = np.nanmin(no_even_small_one)

print("Suma dla każdego wiersza:", row_sums)
print("Średnia dla każdej kolumny:", col_means)
print("Najmniejsza wartość w całej tablicy:", min_value)

Suma dla każdego wiersza: [ 16.  48.  80. 112. 144. 176. 208. 240.]
Średnia dla każdej kolumny: [29. nan 31. nan 33. nan 35. nan]
Najmniejsza wartość w całej tablicy: 1.0


<ipython-input-12-6ff7646227e3>:3: RuntimeWarning: Mean of empty slice
  col_means = np.nanmean(no_even_small_one, axis=0)


In [13]:
# Zad 6
"""Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())
liczby parzyste, które wcześniej zastąpiliśmy wartościami nan
(teraz 1 jeżeli wykonany jest podpunkt pierwszy),
więc przywracamy ten tablicy wygląd oryginalny z tablicy
a_small_one - dla warunku wstawiaj wartość z a_small_one
lub no_even_small_one"""

'Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:\n\nwartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())\nliczby parzyste, które wcześniej zastąpiliśmy wartościami nan\n(teraz 1 jeżeli wykonany jest podpunkt pierwszy),\nwięc przywracamy ten tablicy wygląd oryginalny z tablicy\na_small_one - dla warunku wstawiaj wartość z a_small_one\nlub no_even_small_one'

In [14]:
no_even_small_one = np.where(a_small_one % 2 == 0, np.nan, a_small_one)

no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)

no_even_small_one = np.where(a_small_one % 2 == 0, a_small_one, no_even_small_one)

print("Ostateczna tablica:\n", no_even_small_one)

Ostateczna tablica:
 [[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


In [15]:
# Zad 7
"""Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100
próbkując wartości z rozkładu normalnego standardowego."""

'Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100\npróbkując wartości z rozkładu normalnego standardowego.'

In [16]:
sto_by_sto = np.random.randn(100, 100)
print(sto_by_sto[:5, :5])

[[-0.0128004  -0.74137822 -1.83701976  0.46757752  0.94842282]
 [-0.07766871  1.10426203  0.89808582 -1.038169   -1.45117559]
 [ 0.42082202  0.91979421  0.75600643 -0.84756243 -1.23770041]
 [ 1.55484189 -0.36698334 -0.00282186  2.24644846 -0.22494083]
 [-2.09113317  0.51316074 -0.20144153  0.59222455 -0.20174577]]


In [17]:
# Zad 8
"""Dla tablicy sto_by_sto policz:

wartość średnią w każdym wierszu i kolumnie (oddzielnie),
policz średnią różnicę bezwzględną dla wartości w powyższym
punkcie względem wartości 0 (oddzielnie dla średniej z kolumn
i średniej z wierszy, pamiętam o tym, że operacje na tablicy
numpy wykonywane są w trybie broadcast)."""

'Dla tablicy sto_by_sto policz:\n\nwartość średnią w każdym wierszu i kolumnie (oddzielnie),\npolicz średnią różnicę bezwzględną dla wartości w powyższym\npunkcie względem wartości 0 (oddzielnie dla średniej z kolumn\ni średniej z wierszy, pamiętam o tym, że operacje na tablicy\nnumpy wykonywane są w trybie broadcast).'

In [18]:
row_means = np.mean(sto_by_sto, axis=1)
col_means = np.mean(sto_by_sto, axis=0)
row_mean_abs_diff = np.mean(np.abs(row_means))
col_mean_abs_diff = np.mean(np.abs(col_means))
#print("Średnie wartości w każdym wierszu:", row_means)
#print("Średnie wartości w każdej kolumnie:", col_means)
print("Średnia różnica bezwzględna względem 0 dla średnich wierszy:", row_mean_abs_diff)
print("Średnia różnica bezwzględna względem 0 dla średnich kolumn:", col_mean_abs_diff)

Średnia różnica bezwzględna względem 0 dla średnich wierszy: 0.08396003394284814
Średnia różnica bezwzględna względem 0 dla średnich kolumn: 0.07857740478030868


In [19]:
# Zad 9
"""Stwórz tablicę o wymiarach 1000x1000
uzupełniając ją wartościami losowymi z rozkładu
normalnego standardowego, a następnie posiłkując
się przykładami z labów poprzednich (moduł timeit)
porównaj czasy wykonania dla tej tablicy:

zapisu do pliku tekstowego vs. zapis do pliku
w formacie picle vs. zapis do pliku skompresowanego
(funkcja savez_compressed w dokumentacji biblioteki numpy)
odczytu dla trzech wyżej wymienionych plików."""

'Stwórz tablicę o wymiarach 1000x1000\nuzupełniając ją wartościami losowymi z rozkładu\nnormalnego standardowego, a następnie posiłkując\nsię przykładami z labów poprzednich (moduł timeit)\nporównaj czasy wykonania dla tej tablicy:\n\nzapisu do pliku tekstowego vs. zapis do pliku\nw formacie picle vs. zapis do pliku skompresowanego\n(funkcja savez_compressed w dokumentacji biblioteki numpy)\nodczytu dla trzech wyżej wymienionych plików.'

In [20]:
data = np.random.randn(1000, 1000)

# Funkcje do zapisu

def save_txt():
    np.savetxt("data.txt", data)

def save_pickle():
    with open("data.pkl", "wb") as f:
        pickle.dump(data, f)

def save_compressed():
    np.savez_compressed("data_compressed.npz", data)

# Funkcje do odczytu

def load_txt():
    np.loadtxt("data.txt")

def load_pickle():
    with open("data.pkl", "rb") as f:
        pickle.load(f)

def load_compressed():
    np.load("data_compressed.npz")['arr_0']

# Pomiar czasu
print("Czasy zapisu:")
print("Zapis do TXT:", timeit.timeit(save_txt, number=1))
print("Zapis do Pickle:", timeit.timeit(save_pickle, number=1))
print("Zapis do skompresowanego pliku:", timeit.timeit(save_compressed, number=1))

print("\nCzasy odczytu:")
print("Odczyt z TXT:", timeit.timeit(load_txt, number=1))
print("Odczyt z Pickle:", timeit.timeit(load_pickle, number=1))
print("Odczyt z pliku skompresowanego:", timeit.timeit(load_compressed, number=1))

Czasy zapisu:
Zapis do TXT: 4.0943896480000035
Zapis do Pickle: 0.0222485660000018
Zapis do skompresowanego pliku: 1.7192262270000072

Czasy odczytu:
Odczyt z TXT: 1.0528748609999923
Odczyt z Pickle: 0.00456979500000898
Odczyt z pliku skompresowanego: 0.0781661020000115
